### PR TITLE
Add NordVPN support to resolve #10

### LINKED ISSUE #10: [REQUEST] NordVPN Template
Hi,

Is there any chance you can add a template for NordVPN (https://hub.docker.com/r/azinchen/nordvpn) ? I've tried all day to get it to work... unfortunetly no success.  

Kindly appreciated!

### PR DESCRIPTION
**Pull request by Macleykun**
## Warning we automatically generate the following files, your change(s) will overwritten.
* docs/README.md
* template/portainer-v2-arm32.json
* template/portainer-v2-arm64.json
* template/portainer-v2-amd64.json
* tools/README.md
* docs/AppList.md
* docs/DocumentList.md
* pi-hosted_template/template/portainer-v2.json 

## Please make any changes to these files instead 
* template/apps/`some-application-name.json`
* stack/`some-stack-name.yml` 
* docs/`some-docsname.md`
* tools/`some-script.sh`
* build/info.json

## Checklist

- [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
- [ ] Does your submission pass tests?
- [ ] Have you linted your code locally prior to submission?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you updated documentation, as applicable?1

---
It's my first time making a new stack, i believe it's even easier then adding a container usually. However i do need some help how to set this properly up so it can be merged to fix: https://github.com/pi-hosted/pi-hosted/issues/10.

### CODE REVIEW

**Comment by Macleykun** [comment]
think this is alot better, need testing as i don't have nordvpn:
https://github.com/Macleykun/pi-hosted/blob/patch-1/template/portainer-v2-arm64.json

@shalk3 & @xoste49 can you two perhaps test as you two have talked/requested this template?

**Comment by xoste49** [comment]
> думаю, что это намного лучше, нужно протестировать, так как у меня нет nordvpn: [https://github.com/Macleykun/pi-hosted/blob/patch-1/template/porttainer-v2-arm64.json](https://github.com/Macleykun/pi-hosted/blob/patch-1/template/portainer-v2-arm64.json)
> 
> @shalk3&@xoste49Можете ли вы двое, возможно, проверить, как вы двое говорили/запрашивали этот шаблон?

I don't have nordvpn

**Comment by shalk3** [comment]
I do have nordvpn, but I can't see the template. Is it arm32 or arm64 ?
My workaround atm is using  the  	transmission-openvpn-v4 and routing the deluge internet via the transmission vpn connection :D

**Comment by Macleykun** [comment]
> I do have nordvpn, but I can't see the template. I guess its on arm64 ? Currently running arm32 and lazy to change to 64
> My workaround atm is using the transmission-openvpn-v4 and routing the deluge internet via the transmission vpn connection :D

It should be on all 3 platforms!
Rebuilding but on main now. Just saw I used yaml instead of json :p 
Pretty sure it’s ready to be tested!

Test with: https://raw.githubusercontent.com/Macleykun/pi-hosted/master/template/portainer-v2-arm32.json

**Comment by shalk3** [comment]
> > I do have nordvpn, but I can't see the template. I guess its on arm64 ? Currently running arm32 and lazy to change to 64
> > My workaround atm is using the transmission-openvpn-v4 and routing the deluge internet via the transmission vpn connection :D
> 
> It should be on all 3 platforms! Rebuilding but on main now. Just saw I used yaml instead of json :p Pretty sure it’s ready to be tested!
> 
> Test with: https://raw.githubusercontent.com/Macleykun/pi-hosted/master/template/portainer-v2-arm32.json

Still not showing up, with both the old and your App Templates URLs
Screenshot 2022-11-13 at 22-50-00 Portainer local

**Comment by Macleykun** [comment]
> > > I do have nordvpn, but I can't see the template. I guess its on arm64 ? Currently running arm32 and lazy to change to 64
> > > My workaround atm is using the transmission-openvpn-v4 and routing the deluge internet via the transmission vpn connection :D
> > 
> > 
> > It should be on all 3 platforms! Rebuilding but on main now. Just saw I used yaml instead of json :p Pretty sure it’s ready to be tested!
> > Test with: https://raw.githubusercontent.com/Macleykun/pi-hosted/master/template/portainer-v2-arm32.json
> 
> Still not showing up, with both the old and your App Templates URLs Screenshot 2022-11-13 at 22-50-00 Portainer local

It’s coming :) had to do this on a tablet, saw that it’s now parsing correctly on both branches. Try once more :D !

**Comment by shalk3** [comment]
> > > > I do have nordvpn, but I can't see the template. I guess its on arm64 ? Currently running arm32 and lazy to change to 64
> > > > My workaround atm is using the transmission-openvpn-v4 and routing the deluge internet via the transmission vpn connection :D
> > > 
> > > 
> > > It should be on all 3 platforms! Rebuilding but on main now. Just saw I used yaml instead of json :p Pretty sure it’s ready to be tested!
> > > Test with: https://raw.githubusercontent.com/Macleykun/pi-hosted/master/template/portainer-v2-arm32.json
> > 
> > 
> > Still not showing up, with both the old and your App Templates URLs Screenshot 2022-11-13 at 22-50-00 Portainer local
> 
> It’s coming :) had to do this on a tablet, saw that it’s now parsing correctly on both branches. Try once more :D !

Screenshot 2022-11-13 at 22-58-43 Portainer local

**Comment by Macleykun** [comment]
> > > > > I do have nordvpn, but I can't see the template. I guess its on arm64 ? Currently running arm32 and lazy to change to 64
> > > > > My workaround atm is using the transmission-openvpn-v4 and routing the deluge internet via the transmission vpn connection :D
> > > > 
> > > > 
> > > > It should be on all 3 platforms! Rebuilding but on main now. Just saw I used yaml instead of json :p Pretty sure it’s ready to be tested!
> > > > Test with: https://raw.githubusercontent.com/Macleykun/pi-hosted/master/template/portainer-v2-arm32.json
> > > 
> > > 
> > > Still not showing up, with both the old and your App Templates URLs Screenshot 2022-11-13 at 22-50-00 Portainer local
> > 
> > 
> > It’s coming :) had to do this on a tablet, saw that it’s now parsing correctly on both branches. Try once more :D !
> 
> Screenshot 2022-11-13 at 22-58-43 Portainer local

https://raw.githubusercontent.com/Macleykun/pi-hosted/master/template/portainer-v2-arm32.json
^this one should work now
EE491751-67A5-4B55-BF2C-6A6B2C3F9EE5

**Comment by shalk3** [comment]
Can confirm it works! 
Screenshot 2022-11-13 at 23-14-20 Portainer local

**Comment by shalk3** [comment]
Btw. your hostname is still visible in your screencapture

**Comment by Macleykun** [comment]
> Can confirm it works!
> Screenshot 2022-11-13 at 23-14-20 Portainer local

Awsome! I believe it’s then ready to be merged thx
Local is still ok for a host name to show, will remove just in case thanks!

**Pull request merged**
